on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        if: github.owner == 'dsp-testing'
        env:
          NOT_FORK: ${{ secrets.NOT_FORK }}
        steps:
        - uses: actions/checkout@v2
          if: env.NOT_FORK != ''
        - run: echo "hello world"
          if: env.NOT_FORK != ''
