on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        env:
          NOT_FORK: ${{ secrets.NOT_FORK }}
        if: env.NOT_FORK != ''
        steps:
        - uses: actions/checkout@v2
        - run: echo "hello world"
