on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        if: ${{ secrets.NOT_FORK }} != ''
        steps:
        - uses: actions/checkout@v2
        - run: echo "hello world"
